# -*- coding: utf-8 -*-
"""Centauri Apps - One Week Project_Febriansah Dirgantara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pV-9jn_BAY8n7XYvNfNH0cO1XsjgrsJx

#Centauri App - One Week Project
# Fitur-fitur Sistem Peminjaman Alat Elektronik:

1. **Inisiasi Nama Software**
   - Fitur ini memungkinkan pengguna untuk menginisiasi nama software saat pertama kali menjalankan sistem.

2. **Pendaftaran Anggota**
   - Fitur ini memungkinkan pengguna untuk mendaftarkan diri sebagai anggota dengan menyediakan informasi seperti nama, alamat, nomor telepon, username, dan password.

3. **Login**
   - Pengguna dapat melakukan login ke dalam sistem dengan menggunakan username dan password yang telah didaftarkan.

4. **Cari dan Daftar Alat Elektronik**
   - Pengguna dapat mencari alat elektronik berdasarkan kategori tertentu dan melihat daftar alat yang sesuai dengan kriteria pencarian.

5. **Pinjam Alat Elektronik**
   - Fitur ini memungkinkan pengguna untuk meminjam alat elektronik yang tersedia dalam sistem.
   - `admin, staff` dapat membuat request peminjaman untuk user

6. **Kembalikan Alat Elektronik**
   - Pengguna dapat mengembalikan alat elektronik yang telah dipinjam sebelumnya.

7. **Status Ketersediaan Alat Elektronik**
   - Fitur ini memungkinkan pengguna untuk melihat status ketersediaan alat elektronik, apakah alat tersebut tersedia untuk dipinjam atau sedang dipinjam oleh pengguna lain.

8. **Riwayat Peminjaman**
   - Pengguna dapat melihat riwayat peminjaman alat elektronik, baik secara pribadi.
   - `admin, staff` dapat melihat riwayat user berdasarkan `nama` dan seluruh Daftar Riwayat dari berbagi User

9. **Manajemen Data Alat Elektronik**
   - Admin memiliki akses untuk menambah, menghapus, atau mengubah data alat elektronik dalam sistem.

10. **Manajemen Akun**
    - Admin dapat mengelola akun pengguna, termasuk menambah, menghapus, mengubah, atau melihat profil akun.

11. **Logout**
    - Pengguna dapat keluar dari sesi login mereka.

12. **Exit**
    - Pengguna dapat keluar dari sistem secara keseluruhan.

###Inisiasi()
  - Insiasi Nama Software Berdasarkan inputan dari Pengguna Software
"""

import datetime
def inisiasi():
  print("Welcome To Centauri Apps\n")
  nama_software = input("Ketikan Nama Software yang baru: \n")
  print(f"Software Terinisiasi: {nama_software}")
  return nama_software

"""###Penyimpanan Data (List Tuple)
 - Menyimpan variabel `anggota` untuk Profil admin, staff dan user sebagai pengunjung yang terikat terhadap akunnya masing masing
 - Menyimpan data peminjaman pada List `riwayat_peminjaman` yang di lakukan oleh user
"""

anggota = [
    {
    'nama': 'febri-admin',
    'alamat': 'Singapore',
    'nomor_telepon': '6282321555232',
    'nik': '320000000',
    'username': 'admin',
    'password': 'admin',
    'level': 'admin'
    },
    {
    'nama': 'febri-staff',
    'alamat': 'Singapore',
    'nomor_telepon': '6282321555232',
    'nik': '320000000',
    'username': 'staff',
    'password': 'staff',
    'level': 'staff'
    },
    {
    'nama': 'febri-pengunjung',
    'alamat': 'Singapore',
    'nomor_telepon': '6282321555232',
    'nik': '320000000',
    'username': 'pengunjung',
    'password': 'pengunjung',
    'level': 'pengunjung'
    }
  ]

alat_proyektor = [
       {'nomor_inventaris': 'A001', 'nama': 'Proyektor 1', 'deskripsi': 'Proyektor untuk presentasi', 'status': 'tersedia'},
       {'nomor_inventaris': 'A002', 'nama': 'Proyektor 2', 'deskripsi': 'Proyektor untuk meeting', 'status': 'tersedia'}
]

riwayat_peminjaman = []

"""###registrasi_anggota()
  - Function untuk registrasi pengguna untuk membuat profil
  - membuat akun pengguna yang terhubung pada profil pengguna

Spesifikasi Parameter
- A. Profil
  1. Nama `(String)`
  2. Alamat `(string)`
  3. Nomor Telepon `(Integer)`
  4. NIK `(Integer)`

- B. Akun
  1. Username `(String)`
  2. Password `(String)`


####Note: `append()`
  - Menyisipkan Element ke dalam Tuple List yang di gunakan sebagai template dengan acuan variabel yang di beri nama `anggota`
"""

def registrasi_anggota():
  nama = input("Nama Kamu: ")
  alamat = input("Alamat/Domisili: ")
  nomor_telepon = input("Hp/Wahtsapp: ")
  nik = int(input("NIK (16 Digits): "))
  username = input("Username Baru: ")
  password = input("Password Baru: ")
  anggota.append({
    'nama': nama,
    'alamat': alamat,
    'nomor_telepon': nomor_telepon,
    'nik': nik,
    'username': username,
    'password': password,
    'level': 'pengunjung'
    })

"""###verifikasi()
 - Function untuk akses ke dalam Centauri Apps
 - Multi Level login detection (pengunjung, staff atau admin)
"""

def verifikasi():
  username = input("Username Anda: ")
  password = input("Password Anda: ")
  check = next((akun for akun in anggota if akun['username'] == username and akun['password'] == password), None)
  if check:
    if check['level'] != 'admin':
      print(f"Selamat Datang, {check['nama']}! Anda Berhasil Login Sebagai {check['level']}")
      return check
    else:
      print(f"Selamat Datang, {check['nama']}! Anda Berhasil Login Sebagai {check['level']}")
      return check
  else:
    print("Username atau Password Salah !\n")
    return None

"""####Penjelasan variabel `check`, dan function `next()`

 - `check` akan melakukan perulangan pada variabel `anggota` dan hasil dari pengecekan akan di sebut sebagai `akun` lalu menyeleksi apakah terdapat nilai dari inputan `username` dan `password` yang cocok/terdaftar, jika hasilnya positif maka akan mengembalikan nilai secara default sebagau `True`, namun jika tidak maka akan mengembalikan output sebagai `None` atau `false` dan akan mencetak bahwa `akun tidak terdaftar`

 - function `next()` di gunakan untuk mengembalikan nilai `iterator` pada hal ini adalah `akun` yang kita gunakan sebagai `iterator`, setiap rumpun iterasi di pisahkan oleh `{}` sebagai `satu rumpun iterator dalam list`

####daftar_alat()
  - Mencari alat berdasarkan Nama atau Deskripsi
  - Menampilkan Daftar Alat sesuai Pencarian
  - Memunculkan `NOmor Inventaris, Nama, deskripsi` dan `status` dari barang yang di cari
"""

def daftar_alat():
  cari_barang = input("Masukan Nama/Deskripsi Alat: ")
  hasil_pencarian =[
      alat for alat in alat_proyektor
      if cari_barang.lower() in alat['nama'].lower()
      or cari_barang.lower() in alat['deskripsi'].lower()
      ]
  if hasil_pencarian:
        for alat in hasil_pencarian:
            print(f"Nomor Inventaris: {alat['nomor_inventaris']}, Nama: {alat['nama']}, Deskripsi: {alat['deskripsi']}, Status: {alat['status']}")
  else:
        print("Tidak ada alat yang ditemukan dengan kategori tersebut.")

"""####pinjam_alat_oleh_admin_staff()
 - Admin/Staff Menginput Nomor inventaris dan Nama Peminjam
 - Peminjaman di lakukan beradasarkan `nomor inventaris barang`
 - mengecek status barang apakan `tersedia` atau sedang `dipinjam`
 - mencatat siapa peminjam, tanggal peminjaman dengan maksimal 7 hari pengembalian


"""

def pinjam_alat_oleh_admin_staff(user):
    nomor_inventaris = input("Masukkan nomor inventaris alat yang ingin dipinjam: ")
    nama_anggota = input("Masukan Nama Peminjam")
    alat = next((a for a in alat_proyektor if a['nomor_inventaris'] == nomor_inventaris), None)
    if alat and alat['status'] == 'tersedia':
        alat['status'] = 'dipinjam'
        tanggal_peminjaman = datetime.datetime.now()
        tanggal_pengembalian = tanggal_peminjaman + datetime.timedelta(days=7)
        riwayat_peminjaman.append({'nomor_inventaris': nomor_inventaris, 'nama_anggota': nama_anggota, 'tanggal_peminjaman': tanggal_peminjaman, 'tanggal_pengembalian': tanggal_pengembalian})
        print(f"Alat {alat['nama']} berhasil dipinjam oleh {nama_anggota}. Tanggal pengembalian: {tanggal_pengembalian}")
    else:
        print("Alat tidak tersedia untuk dipinjam.")

"""####pinjam_alat()
 - Sisi User
 - Peminjaman di lakukan beradasarkan `nomor inventaris barang`
 - mengecek status barang apakan `tersedia` atau sedang `dipinjam`
 - mencatat siapa peminjam (dalam hal ini akun pengunjung), tanggal peminjaman dengan maksimal 7 hari pengembalian
"""

def pinjam_alat(user):
    nomor_inventaris = input("Masukkan nomor inventaris alat yang ingin dipinjam: ")
    nama_anggota = input("Masukan Nama Peminjam")
    alat = next((a for a in alat_proyektor if a['nomor_inventaris'] == nomor_inventaris), None)
    if alat and alat['status'] == 'tersedia':
        alat['status'] = 'dipinjam'
        tanggal_peminjaman = datetime.datetime.now()
        tanggal_pengembalian = tanggal_peminjaman + datetime.timedelta(days=7)
        riwayat_peminjaman.append({'nomor_inventaris': nomor_inventaris, 'nama_anggota': user['nama'], 'tanggal_peminjaman': tanggal_peminjaman, 'tanggal_pengembalian': tanggal_pengembalian})
        print(f"Alat {alat['nama']} berhasil dipinjam oleh {user['nama']}. Tanggal pengembalian: {tanggal_pengembalian}")
    else:
        print("Alat tidak tersedia untuk dipinjam.")

"""####kembalikan_alat()
 - mengembalikan alat berdasarkan nomor inventaris
 - mengkalkulasi keterlambatan per hari yakni 10.000 rupiah





"""

def kembalikan_alat():
    nomor_inventaris = input("Masukkan nomor inventaris alat yang akan dikembalikan: ")
    alat = next((a for a in alat_proyektor if a['nomor_inventaris'] == nomor_inventaris), None)
    if alat and alat['status'] == 'dipinjam':
        alat['status'] = 'tersedia'
        tanggal_pengembalian = datetime.datetime.now()
        for peminjaman in riwayat_peminjaman:
            if peminjaman['nomor_inventaris'] == nomor_inventaris:
                if peminjaman['tanggal_pengembalian'] < tanggal_pengembalian:
                    keterlambatan = (tanggal_pengembalian - peminjaman['tanggal_pengembalian']).days
                    if keterlambatan > 0:
                        denda = keterlambatan * 10000  # contoh denda Rp10,000 per hari
                        print(f"Pengembalian terlambat {keterlambatan} hari. Denda yang harus dibayarkan: Rp{denda}")
                break
        print(f"Alat {alat['nama']} berhasil dikembalikan.")
    else:
        print("Alat tidak ditemukan atau sudah tersedia.")

"""####status_alat()
 - Track status alat berdasarkan nomor inventaris menampilkan `sisa watu peminjaman`
"""

def status_alat():
    nomor_inventaris = input("Masukkan nomor inventaris alat: ")
    alat = next((a for a in alat_proyektor if a['nomor_inventaris'] == nomor_inventaris), None)
    if alat:
        print(f"Status alat {alat['nama']}: {alat['status']}")
        if alat['status'] == 'dipinjam':
            peminjaman = next((r for r in riwayat_peminjaman if r['nomor_inventaris'] == nomor_inventaris), None)
            if peminjaman:
                sisa_hari = (peminjaman['tanggal_pengembalian'] - datetime.datetime.now()).days
                print(f"Sisa waktu peminjaman: {sisa_hari} hari")
    else:
        print("Alat tidak ditemukan.")

"""####riwayat()

 - riwayat peminjaman dengan `level akses admin`
 - melihat peminjaman pribadi `level admin`
 - peminjaman seluruh anggota, dengan mencari anggota berdasarkan `nama`
 - Jika level `pengunjung`, akan menampilkan alat yang di pinjam berdasarkan pemilik akun yang sedang di gunakan

"""

def riwayat(user):
    if user['level'] == 'admin' or user['level'] == 'staff':
        pilihan = input("Lihat riwayat peminjaman (1) pribadi atau (2) keseluruhan? ")
        if pilihan == '1':
            nama_anggota = input("Masukkan nama anggota: ")
            riwayat_pribadi = [r for r in riwayat_peminjaman if r['nama_anggota'] == nama_anggota]
            for r in riwayat_pribadi:
                print(f"Nomor Inventaris: {r['nomor_inventaris']}, Tanggal Peminjaman: {r['tanggal_peminjaman']}, Tanggal Pengembalian: {r['tanggal_pengembalian']}")
        elif pilihan == '2':
            for r in riwayat_peminjaman:
                print(f"Nomor Inventaris: {r['nomor_inventaris']}, Nama Anggota: {r['nama_anggota']}, Tanggal Peminjaman: {r['tanggal_peminjaman']}, Tanggal Pengembalian: {r['tanggal_pengembalian']}")
        else:
            print("Pilihan tidak valid.")
    else:
        riwayat_pribadi = [r for r in riwayat_peminjaman if r['nama_anggota'] == user['nama']]
        for r in riwayat_pribadi:
            print(f"Nomor Inventaris: {r['nomor_inventaris']}, Tanggal Peminjaman: {r['tanggal_peminjaman']}, Tanggal Pengembalian: {r['tanggal_pengembalian']}")

"""####manajemen_alat()
 - akses manajemen level admin untuk menambahkan proyektor dengan parameter `nama_alat, deskripsi, nomor_inventaris`
 - hapus proyektor berdasarkan `nomor_inventaris`
 - merubah informasi alat berdasarkan `nomor_inventaris`
"""

def manajemen_alat(user):
    if user['level'] == 'admin':
        pilihan = input("Manajemen alat: (1) Tambah, (2) Hapus, (3) Ubah? ")
        if pilihan == '1':
            nomor_inventaris = input("Masukkan nomor inventaris: ")
            nama = input("Masukkan nama alat: ")
            deskripsi = input("Masukkan deskripsi alat: ")
            alat_proyektor.append({'nomor_inventaris': nomor_inventaris, 'nama': nama, 'deskripsi': deskripsi, 'status': 'tersedia'})
            print("Alat berhasil ditambahkan.")
        elif pilihan == '2':
            nomor_inventaris = input("Masukkan nomor inventaris alat yang akan dihapus: ")
            alat_proyektor[:] = [a for a in alat_proyektor if a['nomor_inventaris'] != nomor_inventaris]
            print("Alat berhasil dihapus.")
        elif pilihan == '3':
            nomor_inventaris = input("Masukkan nomor inventaris alat yang akan diubah: ")
            alat = next((a for a in alat_proyektor if a['nomor_inventaris'] == nomor_inventaris), None)
            if alat:
                nama = input(f"Masukkan nama alat baru (sebelumnya {alat['nama']}): ")
                deskripsi = input(f"Masukkan deskripsi alat baru (sebelumnya {alat['deskripsi']}): ")
                alat['nama'] = nama
                alat['deskripsi'] = deskripsi
                print("Alat berhasil diubah.")
            else:
                print("Alat tidak ditemukan.")
        else:
            print("Pilihan tidak valid.")
    else:
        print("Anda tidak memiliki hak akses untuk mengelola data alat elektronik.")

"""####manajemen_akun()
 - menambahkan `profil` dan `akun`
 - hapus `akun` berdasarkan `username`
 - ubah `akun` berdasarkan `username`
 - view `akun` berdasarkan `username`


"""

def manajemen_akun():
    pilihan = input("Manajemen akun: (1) Tambah, (2) Hapus, (3) Ubah, (4) Lihat Profil? ")
    if pilihan == '1':
        nama = input("Masukkan nama: ")
        alamat = input("Masukkan alamat: ")
        nomor_telepon = input("Masukkan nomor telepon: ")
        username = input("Masukkan username: ")
        password = input("Masukkan password: ")
        nik = input("Masukan NIK: ")
        level = input("Masukkan level (pengunjung/staff/admin): ")
        anggota.append({
            'nama': nama,
            'alamat': alamat,
            'nomor_telepon': nomor_telepon,
            'nik': nik,
            'username': username,
            'password': password,
            'level': level
            })
        print("Akun berhasil ditambahkan.")
    elif pilihan == '2':
        username = input("Masukkan username akun yang akan dihapus: ")
        anggota[:] = [a for a in anggota if a['username'] != username]
        print("Akun berhasil dihapus.")
    elif pilihan == '3':
        username = input("Masukkan username akun yang akan diubah: ")
        akun = next((a for a in anggota if a['username'] == username), None)
        if akun:
            nama = input(f"Masukkan nama baru (sebelumnya {akun['nama']}): ")
            alamat = input(f"Masukkan alamat baru (sebelumnya {akun['alamat']}): ")
            nomor_telepon = input(f"Masukkan nomor telepon baru (sebelumnya {akun['nomor_telepon']}): ")
            nik = input(f"Masukkan NIK (sebelumnya {akun['nik']}): ")
            password = input(f"Masukkan password baru (sebelumnya {akun['password']}): ")
            level = input(f"Masukkan level baru (sebelumnya {akun['level']}): ")
            akun['nama'] = nama
            akun['alamat'] = alamat
            akun['nomor_telepon'] = nomor_telepon
            akun['nik'] = nik
            akun['password'] = password
            akun['level'] = level
            print("Akun berhasil diubah.")
        else:
            print("Akun tidak ditemukan.")
    elif pilihan == '4':
        username = input("Masukkan username akun yang akan dilihat: ")
        akun = next((a for a in anggota if a['username'] == username), None)
        if akun:
            print(f"Nama: {akun['nama']}")
            print(f"Alamat: {akun['alamat']}")
            print(f"Nomor Telepon: {akun['nomor_telepon']}")
            print(f"NIK: {akun['nik']}")
            print(f"Username: {akun['username']}")
            print(f"Level: {akun['level']}")
        else:
            print("Akun tidak ditemukan.")
    else:
        print("Pilihan tidak valid.")

"""#### main()

- Inisiasi `nama_software`
- Menampilkan Halaman Utama
  - Login
  - Daftar Anggota
  - Exit

- Pengunjung
   1. Cari dan Daftar Alat Elektronik
   2. Status Ketersediaan Alat Elektronik
   3. Riwayat Peminjaman (Akun pribadi)
   4. Logout
   5. Exit


- Staff
  1. Cari dan Daftar Alat Elektronik
  2. Pinjam Alat Elektronik" (Untuk Pengunjung)
  3. Kembalikan Alat Elektronik
  4. Status Ketersediaan Alat Elektronik
  5. Riwayat Peminjaman (Cari Riwayat Berdasarkan Nama User)
  6. Logout
  7. Exit

- Admin
  1. Cari dan Daftar Alat Elektronik
  2. Pinjam Alat Elektronik (Untuk Pengunjung)
  3. Kembalikan Alat Elektronik
  4. Status Ketersediaan Alat Elektronik
  5. Riwayat Peminjaman (Cari Riwayat Berdasarkan User
  6. Manajemen Data Alat Elektronik
  7. Manajemen Akun
  8. Logout
  9. Exit

"""

def main():
    software_name = inisiasi()
    user = None
    while True:
        if not user:
            print("\n1. Login")
            print("2. Daftar Anggota")
            print("3. Exit")
            pilihan = input("Pilih menu: ")
            if pilihan == '1':
                user = verifikasi()
            elif pilihan == '2':
                registrasi_anggota()
            elif pilihan == '3':
                print("Terima kasih telah menggunakan sistem ini!")
                break
            else:
                print("Pilihan tidak valid. Silakan coba lagi.")
        else:
            print(f"\n-- {software_name} --")
            if user['level'] == 'admin':
                print("1. Cari dan Daftar Alat Elektronik")
                print("2. Pinjam Alat Elektronik (Untuk Pengunjung)")
                print("3. Kembalikan Alat Elektronik")
                print("4. Status Ketersediaan Alat Elektronik")
                print("5. Riwayat Peminjaman")
                print("6. Manajemen Data Alat Elektronik")
                print("7. Manajemen Akun")
                print("8. Logout")
                print("9. Exit")
                pilihan = input("Pilih menu: ")
                if pilihan == '1':
                    daftar_alat()
                elif pilihan == '2':
                    pinjam_alat_oleh_admin_staff(user)
                elif pilihan == '3':
                    kembalikan_alat()
                elif pilihan == '4':
                    status_alat()
                elif pilihan == '5':
                    riwayat(user)
                elif pilihan == '6':
                    manajemen_alat(user)
                elif pilihan == '7':
                    manajemen_akun()
                elif pilihan == '8':
                    user = None
                elif pilihan == '9':
                    print("Terima kasih telah menggunakan sistem ini!")
                    break
                else:
                    print("Pilihan tidak valid. Silakan coba lagi.")
            elif user['level'] == 'staff':
                print("1. Cari dan Daftar Alat Elektronik")
                print("2. Pinjam Alat Elektronik(Untuk Pengunjung)")
                print("3. Kembalikan Alat Elektronik")
                print("4. Status Ketersediaan Alat Elektronik")
                print("5. Riwayat Peminjaman")
                print("6. Logout")
                print("7. Exit")
                pilihan = input("Pilih menu: ")
                if pilihan == '1':
                    daftar_alat()
                elif pilihan == '2':
                    pinjam_alat_oleh_admin_staff(user)
                elif pilihan == '3':
                    kembalikan_alat()
                elif pilihan == '4':
                    status_alat()
                elif pilihan == '5':
                    riwayat(user)
                elif pilihan == '6':
                    user = None
                elif pilihan == '7':
                    print("Terima kasih telah menggunakan sistem ini!")
                    break
                else:
                    print("Pilihan tidak valid. Silakan coba lagi.")
            elif user['level'] == 'pengunjung':
                print("1. Cari dan Daftar Alat Elektronik")
                print("2. Pinjam Alat")
                print("3. Status Ketersediaan Alat Elektronik")
                print("4. Riwayat Peminjaman")
                print("4. Logout")
                print("5. Exit")
                pilihan = input("Pilih menu: ")
                if pilihan == '1':
                    daftar_alat()
                elif pilihan == '2':
                    pinjam_alat(user)
                elif pilihan == '3':
                    status_alat()
                elif pilihan == '4':
                    riwayat(user)
                elif pilihan == '5':
                    user = None
                elif pilihan == '6':
                    print("Terima kasih telah menggunakan sistem ini!")
                    break
                else:
                    print("Pilihan tidak valid. Silakan coba lagi.")

main()
